### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: OY1Bgj7fb6bb95fa7204e67ahcalVgf1

origin=64999&destination=64942&weight=1000&courier=jne